import requests

url = 'http://127.0.0.1:5000/predict/vessel_info'

data = {
    "text": '''
    FROM SnC MARITIME SEOUL KOREA 82-2-778-0283 DRY@SNCMARITIME.COM - SS Kang

    CLOSE LOCAL OWNERS HV : -

    OPEN VIZAG,    
    27th JULY

    TRY 1tct or 2-3LL (upto 9/22)

    VSL PARTICULAR:

    =========

    MV GLOVIS MELODY
    DWT 55,705 MT ON 12.868M SSW TPC 57.1
    BUILT NOV  2012
    FLAG BAHAMAS
    GEARED SINGLE DECK BULK CARRIER
    GRT/NRT 32,545/18,528
    LOA/BEAM 187.88M/32.26M
    CARGO CAPA GRAIN ABT 70,761CBM, BALE ABT 68,290 CBM
    CRANES  4X30 .0MT SWL (HOOK MODE) / 24.0MT SWL (GRAB MODE) GRAB 4 GRABS(14CBM)
    ADA

    SPEED/CONS:
    ABT 13.20 KN ON ABT 26.2 MT IFO (BALLAST)
    ABT 13.20 KN ON ABT 28.2 MT IFO (LADEN)
    IN PORT - ABT 3.0 MT IFO PER DAY IDLE / ABT 4.5 MT IFO PER DAY WORKING

    THE SPEED/CONSUMPTION OF THE VESSEL IS ALWAYS TO BE CONSIDERED AS AVERAGE SPEED/CONSUMPTION IN FULLY BALLAST/ LADEN CONDITION AND UNDER GOOD WEATHER CONDITIONS WHICH FOR THE PURPOSE OF THIS C/P ARE DEFINED AS NO ADVERSE CURRENT, NEGATIVE INFLUENCE OF SWELL, MODERATE SEA, WIND NOT EXCEEDING BEAUFORT FORCE 4 AND/OR DOUGLAS SEA STATE 3(MEANS SIGNIFICANT WAVE HEIGHT LESS THAN 1.25M) AT THE CONDITION OF CLEAN BOTTOM IN OPEN, CALM AND DEEP SEA CONDITION WITH MINIMUM 24 HOURS STEAMING TIME, WITH EVEN KEEL CONDITION. POSITIVE CURRENT SHALL NOT BE USED IN DIMINISHING VESSEL'S PERFORMANCE. VESSEL HAS LIBERTY TO MDO/DMA WHEN MANUEVERING IN SHALLOW / NARROW / BUSY / ONFINED AND RESTRICTED WATERS, PASSING FROM STRAITS, CANALS, RIVERS, BERTHING / UNBERTHING, IN / OUT PORTS, DURING BAD WEATHER AND HEAVY SWELLS, IF REQUIRED. THE WORD “ABOUT” UNDER THIS FIXTURE AS WEATHER APPLY TO BOTH HER “SPEED(S)” AND “CONSUMPTION” IT IS DEFINED AS A TOLERANCE OF 0.5KT ON “SPEED” AND A TOLERANCE OF 5% ON BUNKER CONSUMPTION.

    ECO SPEED (WOG, FOR GUIDANCE ONLY):
    ABT 12.2 KN ON ABT 25.3 MT IFO
    ALL DETAILS ABOUT AND GIVEN IN GOOD FAITH

    B,RGDS / SS Kang (강석산)

    DIR : 822 778 0283
    MOB : 82 10 8751 5308
    DRY@SNCMARITIME.COM
    SKYPE : KANGCHO29@HOTMAIL.COM
    '''
}

response = requests.post(url, json=data)

print(response.status_code)
if response.status_code == 200:
    print(response.json())
else:
    print(f"Error: {response.status_code}")
